# Generated by Django 5.1.2 on 2024-10-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_price', models.FloatField(null=True)),
                ('close_price', models.FloatField(null=True)),
                ('predicted_close_price', models.FloatField(null=True)),
                ('high_price', models.FloatField(null=True)),
                ('low_price', models.FloatField(null=True)),
                ('volume', models.IntegerField(null=True)),
                ('date', models.DateField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
